### ISSUE TITLE
17º Encontro

### ISSUE THREAD

**Issue by filipebarcos** [guru-ce/guru-ce.github.io#16]
Issue para acompanhamento de Evento

- [x] Lançar CFP (http://call4paperz.com/events/17-encontro-guru-ce)
- [x] Lançar Inscrições (http://www.eventick.com.br/17o-encontro-do-guru-ce)
- [x] Post no Blog (https://github.com/guru-ce/guru-ce.github.io/pull/19)
- [x] Escolher local (https://github.com/guru-ce/guru-ce.github.io/pull/21)
- [x] Contratar Coffee Break
- [x] Escolher palestras
- [x] Atualização final do site (palestrantes + local)

**Comment by filipebarcos** [comment]
Sobre o local o que vocês acham? Deveriam continuar com a Elephant? Ou tentar outro local? Fiquei interessando em tentar outro coworking por aqui. O motivo da mudança é tentar procurar um local melhor (não que a Elephant seja ruim), mas a Elephant queria doação de alimentos e também pediu lista de inscritos para newsletter, então pensei e tentar algo novo.

**Comment by dehvmartins** [comment]
Eu acho bacana e existem outros coworkings, a gente pode experimentar.

**Comment by herminiotorres** [comment]
tem um coworking, ali onde é a livraria cultura.

**Comment by filipebarcos** [comment]
Fechando a issue. Parabéns aos organizadores
