### ISSUE TITLE
Criar email

### ISSUE THREAD

**Issue by herminiotorres** [guru-ce/guru-ce.github.io#27]
#### Lista:
- [x] Criar email genérico, por exemplo: `guruce@gmail.com`.
- [x] Criar filtros no email.
- [x] Criar redirecionamento para os envolvidos.

**Comment by herminiotorres** [comment]
quem pode cuidar dessa todo?

**Comment by franzejr** [comment]
Alguém se opoem a guruce42? O guru-ce, guruce  e guru_ce não pode... :(

**Comment by franzejr** [comment]
@herminiotorres @filipebarcos @dehvmartins e-mail criado. Preciso do e-mail de vocês para colocar no redirecionamento. Manda pelo slack!

guruce42

**Comment by herminiotorres** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by franzejr** [comment]
Tudo feito.
