### ISSUE TITLE
Primeiro encontro de 2016

### ISSUE THREAD

**Issue by filipebarcos** [guru-ce/guru-ce.github.io#32]
- [x] Definir data/horário
- [x] Atualizar site
- [x] Criar CFP
- [x] Adicionar evento no Eventick
- [ ] ~~Patrocínio~~
- [x] Divulgação redes sociais
- [x] Local (Atlântico)
- [x] Escolha de Palestrantes
- [ ] Coffeebreak

**Comment by filipebarcos** [comment]
Sugiro dia 16/01. Melhor ainda seria no período da manhã.

**Comment by gurgelrenan** [comment]
Acho que de manhã é mais proveitoso mesmo.

**Comment by franzejr** [comment]
Local: [Instituto Atlântico](http://www.atlantico.com.br/)

**Comment by plcosta** [comment]
Podemos fechar essa issue? @gurgelrenan @filipebarcos
