### ISSUE TITLE
Um BOT irado pro slack

### ISSUE THREAD

**Issue by fernandodev** [guru-ce/guru-ce.github.io#42]
Vamo animar aí esse slack.. o mundo é dos BOT.. yeahhh

**Comment by franzejr** [comment]
Acho massa! Quem sabe um `olar` bot. Tu precisa das permissoes pra começar né, @fernandodev ? O @filipebarcos tem os tokens do slack ?

**Comment by filipebarcos** [comment]
seria irado mesmo, mas como a nossa conta é free, temos um número limitado de integrações. não sei quantas faltam, mas eu sei que recebi uma notificação recente sobre isso n o slack do guru

**Comment by filipebarcos** [comment]
Outra coisa é que temos o https://github.com/guru-ce/gurubot, minha sugestão é adicionar features a ele
